export const nigerianStates = [
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'Federal Capital Territory',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
]

export const nigerianLgaByStates = {
  Abia: [
    'Aba North',
    'Aba South',
    'Arochukwu',
    'Bende',
    'Ikwuano',
    'Isiala Ngwa North',
    'Isiala Ngwa South',
    'Isuikwuato',
    'Obi Ngwa',
    'Ohafia',
    'Osisioma',
    'Ugwunagbo',
    'Ukwa East',
    'Ukwa West',
    'Umuahia North',
    'Umuahia South',
    'Umu Nneochi',
  ],
  Adamawa: [
    'Demsa',
    'Fufore',
    'Ganye',
    'Girei',
    'Gombi',
    'Guyuk',
    'Hong',
    'Jada',
    'Lamurde',
    'Madagali',
    'Maiha',
    'Mayo-Belwa',
    'Michika',
    'Mubi North',
    'Mubi South',
    'Numan',
    'Shelleng',
    'Song',
    'Toungo',
    'Yola North',
    'Yola South',
  ],
  'Akwa Ibom': [
    'Abak',
    'Eastern Obolo',
    'Eket',
    'Esit Eket',
    'Essien Udim',
    'Etim Ekpo',
    'Etinan',
    'Ibeno',
    'Ibesikpo Asutan',
    'Ibiono-Ibom',
    'Ika',
    'Ikono',
    'Ikot Abasi',
    'Ikot Ekpene',
    'Ini',
    'Itu',
    'Mbo',
    'Mkpat-Enin',
    'Nsit-Atai',
    'Nsit-Ibom',
    'Nsit-Ubium',
    'Obot Akara',
    'Okobo',
    'Onna',
    'Oron',
    'Oruk Anam',
    'Udung-Uko',
    'Ukanafun',
    'Uruan',
    'Urue-Offong/Oruko',
    'Uyo',
  ],
  Anambra: [
    'Aguata',
    'Anambra East',
    'Anambra West',
    'Anaocha',
    'Awka North',
    'Awka South',
    'Ayamelum',
    'Dunukofia',
    'Ekwusigo',
    'Idemili North',
    'Idemili South',
    'Ihiala',
    'Njikoka',
    'Nnewi North',
    'Nnewi South',
    'Ogbaru',
    'Onitsha North',
    'Onitsha South',
    'Orumba North',
    'Orumba South',
    'Oyi',
  ],
  Bauchi: [
    'Alkaleri',
    'Bauchi',
    'Bogoro',
    'Damban',
    'Darazo',
    'Dass',
    'Gamawa',
    'Ganjuwa',
    'Giade',
    'Itas/Gadau',
    "Jama'are",
    'Katagum',
    'Kirfi',
    'Misau',
    'Ningi',
    'Shira',
    'Tafawa Balewa',
    'Toro',
    'Warji',
    'Zaki',
  ],
  Bayelsa: [
    'Brass',
    'Ekeremor',
    'Kolokuma/Opokuma',
    'Nembe',
    'Ogbia',
    'Sagbama',
    'Southern Ijaw',
    'Yenagoa',
  ],
  Benue: [
    'Ado',
    'Agatu',
    'Apa',
    'Buruku',
    'Gboko',
    'Guma',
    'Gwer East',
    'Gwer West',
    'Katsina-Ala',
    'Konshisha',
    'Kwande',
    'Logo',
    'Makurdi',
    'Obi',
    'Ogbadibo',
    'Ohimini',
    'Oju',
    'Okpokwu',
    'Otukpo',
    'Tarka',
    'Ukum',
    'Ushongo',
    'Vandeikya',
  ],
  Borno: [
    'Abadam',
    'Askira/Uba',
    'Bama',
    'Bayo',
    'Biu',
    'Chibok',
    'Damboa',
    'Dikwa',
    'Gubio',
    'Guzamala',
    'Gwoza',
    'Hawul',
    'Jere',
    'Kaga',
    'Kala/Balge',
    'Konduga',
    'Kukawa',
    'Kwaya Kusar',
    'Mafa',
    'Magumeri',
    'Maiduguri',
    'Marte',
    'Mobbar',
    'Monguno',
    'Ngala',
    'Nganzai',
    'Shani',
  ],
  'Cross River': [
    'Abi',
    'Akamkpa',
    'Akpabuyo',
    'Bakassi',
    'Bekwarra',
    'Biase',
    'Boki',
    'Calabar Municipal',
    'Calabar South',
    'Etung',
    'Ikom',
    'Obanliku',
    'Obubra',
    'Obudu',
    'Odukpani',
    'Ogoja',
    'Yakurr',
    'Yala',
  ],
  Delta: [
    'Aniocha North',
    'Aniocha South',
    'Bomadi',
    'Burutu',
    'Ethiope East',
    'Ethiope West',
    'Ika North East',
    'Ika South',
    'Isoko North',
    'Isoko South',
    'Ndokwa East',
    'Ndokwa West',
    'Okpe',
    'Oshimili North',
    'Oshimili South',
    'Patani',
    'Sapele',
    'Udu',
    'Ughelli North',
    'Ughelli South',
    'Ukwuani',
    'Uvwie',
    'Warri North',
    'Warri South',
    'Warri South West',
  ],
  Ebonyi: [
    'Abakaliki',
    'Afikpo North',
    'Afikpo South',
    'Ebonyi',
    'Ezza North',
    'Ezza South',
    'Ikwo',
    'Ishielu',
    'Ivo',
    'Izzi',
    'Ohaozara',
    'Ohaukwu',
    'Onicha',
  ],
  Edo: [
    'Akoko-Edo',
    'Egor',
    'Esan Central',
    'Esan North-East',
    'Esan South-East',
    'Esan West',
    'Etsako Central',
    'Etsako East',
    'Etsako West',
    'Igueben',
    'Ikpoba-Okha',
    'Oredo',
    'Orhionmwon',
    'Ovia North-East',
    'Ovia South-West',
    'Owan East',
    'Owan West',
    'Uhunmwonde',
  ],
  Ekiti: [
    'Ado Ekiti',
    'Efon',
    'Ekiti East',
    'Ekiti South-West',
    'Ekiti West',
    'Emure',
    'Gbonyin',
    'Ido Osi',
    'Ijero',
    'Ikere',
    'Ikole',
    'Ilejemeje',
    'Irepodun/Ifelodun',
    'Ise/Orun',
    'Moba',
    'Oye',
  ],
  Enugu: [
    'Aninri',
    'Awgu',
    'Enugu East',
    'Enugu North',
    'Enugu South',
    'Ezeagu',
    'Igbo Etiti',
    'Igbo Eze North',
    'Igbo Eze South',
    'Isi Uzo',
    'Nkanu East',
    'Nkanu West',
    'Nsukka',
    'Oji River',
    'Udenu',
    'Udi',
    'Uzo-Uwani',
  ],
  'Federal Capital Territory': [
    'Abaji',
    'Bwari',
    'Gwagwalada',
    'Kuje',
    'Kwali',
    'Municipal Area Council',
  ],
  Gombe: [
    'Akko',
    'Balanga',
    'Billiri',
    'Dukku',
    'Funakaye',
    'Gombe',
    'Kaltungo',
    'Kwami',
    'Nafada',
    'Shongom',
    'Yamaltu/Deba',
  ],
  Imo: [
    'Aboh Mbaise',
    'Ahiazu Mbaise',
    'Ehime Mbano',
    'Ezinihitte',
    'Ideato North',
    'Ideato South',
    'Ihitte/Uboma',
    'Ikeduru',
    'Isiala Mbano',
    'Isu',
    'Mbaitoli',
    'Ngor Okpala',
    'Njaba',
    'Nkwerre',
    'Nwangele',
    'Obowo',
    'Oguta',
    'Ohaji/Egbema',
    'Okigwe',
    'Onuimo',
    'Orlu',
    'Orsu',
    'Oru East',
    'Oru West',
    'Owerri Municipal',
    'Owerri North',
    'Owerri West',
  ],
  Jigawa: [
    'Auyo',
    'Babura',
    'Biriniwa',
    'Birnin Kudu',
    'Buji',
    'Dutse',
    'Gagarawa',
    'Garki',
    'Gumel',
    'Guri',
    'Gwaram',
    'Gwiwa',
    'Hadejia',
    'Jahun',
    'Kafin Hausa',
    'Kaugama',
    'Kazaure',
    'Kiri Kasama',
    'Kiyawa',
    'Maigatari',
    'Malam Madori',
    'Miga',
    'Ringim',
    'Roni',
    'Sule Tankarkar',
    'Taura',
    'Yankwashi',
  ],
  Kaduna: [
    'Birnin Gwari',
    'Chikun',
    'Giwa',
    'Igabi',
    'Ikara',
    'Jaba',
    "Jema'a",
    'Kachia',
    'Kaduna North',
    'Kaduna South',
    'Kagarko',
    'Kajuru',
    'Kaura',
    'Kauru',
    'Kubau',
    'Kudan',
    'Lere',
    'Makarf',
    'Sabon Gari',
    'Sanga',
    'Soba',
    'Zangon Kataf',
    'Zaria',
  ],
  Kano: [
    'Ajingi',
    'Albasu',
    'Bagwai',
    'Bebeji',
    'Bichi',
    'Bunkure',
    'Dala',
    'Dambatta',
    'Dawakin Kudu',
    'Dawakin Tofa',
    'Doguwa',
    'Fagge',
    'Gabasawa',
    'Garko',
    'Garun Mallam',
    'Gaya',
    'Gezawa',
    'Gwale',
    'Gwarzo',
    'Kabo',
    'Kano Municipal',
    'Karaye',
    'Kibiya',
    'Kiru',
    'Kumbotso',
    'Kunchi',
    'Kura',
    'Madobi',
    'Makoda',
    'Minjibir',
    'Nasarawa',
    'Rano',
    'Rimin Gado',
    'Rogo',
    'Shanono',
    'Sumaila',
    'Takai',
    'Tarauni',
    'Tofa',
    'Tsanyawa',
    'Tudun Wada',
    'Ungogo',
    'Warawa',
    'Wudil',
  ],
  Katsina: [
    'Bakori',
    'Batagarawa',
    'Batsari',
    'Baure',
    'Bindawa',
    'Charanchi',
    'Dandume',
    'Danja',
    'Dan Musa',
    'Daura',
    'Dutsi',
    'Dutsin-Ma',
    'Faskari',
    'Funtua',
    'Ingawa',
    'Jibia',
    'Kafur',
    'Kaita',
    'Kankara',
    'Kankia',
    'Katsina',
    'Kurfi',
    'Kusada',
    "Mai'Adua",
    'Malumfashi',
    'Mani',
    'Mashi',
    'Matazu',
    'Musawa',
    'Rimi',
    'Sabuwa',
    'Safana',
    'Sandamu',
    'Zango',
  ],
  Kebbi: [
    'Aleiro',
    'Arewa Dandi',
    'Argungu',
    'Augie',
    'Bagudo',
    'Birnin Kebbi',
    'Bunza',
    'Dandi',
    'Fakai',
    'Gwandu',
    'Jega',
    'Kalgo',
    'Koko/Besse',
    'Maiyama',
    'Ngaski',
    'Sakaba',
    'Shanga',
    'Suru',
    'Wasagu/Danko',
    'Yauri',
    'Zuru',
  ],
  Kogi: [
    'Adavi',
    'Ajaokuta',
    'Ankpa',
    'Bassa',
    'Dekina',
    'Ibaji',
    'Idah',
    'Igalamela-Odolu',
    'Ijumu',
    'Kabba/Bunu',
    'Kogi',
    'Lokoja',
    'Mopa-Muro',
    'Ofu',
    'Ogori/Magongo',
    'Okehi',
    'Okene',
    'Olamaboro',
    'Omala',
    'Yagba East',
    'Yagba West',
  ],
  Kwara: [
    'Asa',
    'Baruten',
    'Edu',
    'Ekiti',
    'Ifelodun',
    'Ilorin East',
    'Ilorin South',
    'Ilorin West',
    'Irepodun',
    'Isin',
    'Kaiama',
    'Moro',
    'Offa',
    'Oke Ero',
    'Oyun',
    'Pategi',
  ],
  Lagos: [
    'Agege',
    'Ajeromi-Ifelodun',
    'Alimosho',
    'Amuwo-Odofin',
    'Apapa',
    'Badagry',
    'Epe',
    'Eti-Osa',
    'Ibeju-Lekki',
    'Ifako-Ijaiye',
    'Ikeja',
    'Ikorodu',
    'Kosofe',
    'Lagos Island',
    'Lagos Mainland',
    'Mushin',
    'Ojo',
    'Oshodi-Isolo',
    'Shomolu',
    'Surulere',
  ],
  Nasarawa: [
    'Akwanga',
    'Awe',
    'Doma',
    'Karu',
    'Keana',
    'Keffi',
    'Kokona',
    'Lafia',
    'Nasarawa',
    'Nasarawa Egon',
    'Obi',
    'Toto',
    'Wamba',
  ],
  Niger: [
    'Agaie',
    'Agwara',
    'Bida',
    'Borgu',
    'Bosso',
    'Chanchaga',
    'Edati',
    'Gbako',
    'Gurara',
    'Katcha',
    'Kontagora',
    'Lapai',
    'Lavun',
    'Magama',
    'Mariga',
    'Mashegu',
    'Mokwa',
    'Munya',
    'Paikoro',
    'Rafi',
    'Rijau',
    'Shiroro',
    'Suleja',
    'Tafa',
    'Wushishi',
  ],
  Ogun: [
    'Abeokuta North',
    'Abeokuta South',
    'Ado-Odo/Ota',
    'Egbado North',
    'Egbado South',
    'Ewekoro',
    'Ifo',
    'Ijebu East',
    'Ijebu North',
    'Ijebu North East',
    'Ijebu Ode',
    'Ikenne',
    'Imeko-Afon',
    'Ipokia',
    'Obafemi-Owode',
    'Odeda',
    'Odogbolu',
    'Remo North',
    'Shagamu',
  ],
  Ondo: [
    'Akoko North-East',
    'Akoko North-West',
    'Akoko South-East',
    'Akoko South-West',
    'Akure North',
    'Akure South',
    'Ese-Odo',
    'Idanre',
    'Ifedore',
    'Ilaje',
    'Ile Oluji/Okeigbo',
    'Irele',
    'Odigbo',
    'Okitipupa',
    'Ondo East',
    'Ondo West',
    'Ose',
    'Owo',
  ],
  Osun: [
    'Atakunmosa East',
    'Atakunmosa West',
    'Aiyedaade',
    'Aiyedire',
    'Boluwaduro',
    'Boripe',
    'Ede North',
    'Ede South',
    'Egbedore',
    'Ejigbo',
    'Ife Central',
    'Ife East',
    'Ife North',
    'Ife South',
    'Ifedayo',
    'Ifelodun',
    'Ila',
    'Ilesa East',
    'Ilesa West',
    'Irepodun',
    'Irewole',
    'Isokan',
    'Iwo',
    'Obokun',
    'Odo Otin',
    'Ola Oluwa',
    'Olorunda',
    'Oriade',
    'Orolu',
    'Osogbo',
  ],
  Oyo: [
    'Afijio',
    'Akinyele',
    'Atiba',
    'Atisbo',
    'Egbeda',
    'Ibadan North',
    'Ibadan North-East',
    'Ibadan North-West',
    'Ibadan South-East',
    'Ibadan South-West',
    'Ibarapa Central',
    'Ibarapa East',
    'Ibarapa North',
    'Ido',
    'Irepo',
    'Iseyin',
    'Itesiwaju',
    'Iwajowa',
    'Kajola',
    'Lagelu',
    'Ogbomoso North',
    'Ogbomoso South',
    'Ogo Oluwa',
    'Olorunsogo',
    'Oluyole',
    'Ona Ara',
    'Orelope',
    'Ori Ire',
    'Oyo East',
    'Oyo West',
    'Saki East',
    'Saki West',
    'Surulere',
  ],
  Plateau: [
    'Barkin Ladi',
    'Bassa',
    'Bokkos',
    'Jos East',
    'Jos North',
    'Jos South',
    'Kanam',
    'Kanke',
    'Langtang North',
    'Langtang South',
    'Mangu',
    'Mikang',
    'Pankshin',
    "Qua'an Pan",
    'Riyom',
    'Shendam',
    'Wase',
  ],
  Rivers: [
    'Abua/Odual',
    'Ahoada East',
    'Ahoada West',
    'Akuku-Toru',
    'Andoni',
    'Asari-Toru',
    'Bonny',
    'Degema',
    'Eleme',
    'Emohua',
    'Etche',
    'Gokana',
    'Ikwerre',
    'Khana',
    'Obio/Akpor',
    'Ogba/Egbema/Ndoni',
    'Ogu/Bolo',
    'Okrika',
    'Omuma',
    'Opobo/Nkoro',
    'Oyigbo',
    'Port Harcourt',
    'Tai',
  ],
  Sokoto: [
    'Binji',
    'Bodinga',
    'Dange Shuni',
    'Gada',
    'Goronyo',
    'Gudu',
    'Gwadabawa',
    'Illela',
    'Isa',
    'Kebbe',
    'Kware',
    'Rabah',
    'Sabon Birni',
    'Shagari',
    'Silame',
    'Sokoto North',
    'Sokoto South',
    'Tambuwal',
    'Tangaza',
    'Tureta',
    'Wamako',
    'Wurno',
    'Yabo',
  ],
  Taraba: [
    'Ardo Kola',
    'Bali',
    'Donga',
    'Gashaka',
    'Gassol',
    'Ibi',
    'Jalingo',
    'Karim Lamido',
    'Kurmi',
    'Lau',
    'Sardauna',
    'Takum',
    'Ussa',
    'Wukari',
    'Yorro',
    'Zing',
  ],
  Yobe: [
    'Bade',
    'Bursari',
    'Damaturu',
    'Fika',
    'Fune',
    'Geidam',
    'Gujba',
    'Gulani',
    'Jakusko',
    'Karasuwa',
    'Machina',
    'Nangere',
    'Nguru',
    'Potiskum',
    'Tarmuwa',
    'Yunusari',
    'Yusufari',
  ],
  Zamfara: [
    'Anka',
    'Bakura',
    'Birnin Magaji/Kiyaw',
    'Bukkuyum',
    'Bungudu',
    'Gummi',
    'Gusau',
    'Kaura Namoda',
    'Maradun',
    'Maru',
    'Shinkafi',
    'Talata Mafara',
    'Chafe',
    'Zurmi',
  ],
}

export const nigerianGeopoliticalZones = [
  'North Central',
  'North East',
  'North West',
  'South East',
  'South South',
  'South West',
]

export const nigerianStatesByGeopoliticalZones = {
  'North Central': [
    'Benue',
    'Kogi',
    'Kwara',
    'Nasarawa',
    'Niger',
    'Plateau',
    'Federal Capital Territory',
  ],
  'North East': ['Adamawa', 'Bauchi', 'Borno', 'Gombe', 'Taraba', 'Yobe'],
  'North West': [
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Sokoto',
    'Zamfara',
  ],
  'South East': ['Abia', 'Anambra', 'Ebonyi', 'Enugu', 'Imo'],
  'South South': [
    'Akwa Ibom',
    'Bayelsa',
    'Cross River',
    'Delta',
    'Edo',
    'Rivers',
  ],
  'South West': ['Ekiti', 'Lagos', 'Ogun', 'Ondo', 'Osun', 'Oyo'],
}

export const nigerianAreasByStates = {
  Abia: [
    'Umuahia',
    'Aba',
    'Ohafia',
    'Arochukwu',
    'Bende',
    'Isuikwuato',
    'Ohango',
    'Abiriba',
    'Ahaba',
    'Akoli',
    'Alayi',
    'Amaekpu',
    'Amuda',
    'Asaga',
    'Ebem',
    'Item',
    'Nkporo',
    'Ohafor',
    'Ozu Abam',
    'Ubila',
    'Uzuakoli',
  ],
  Adamawa: [
    'Yola',
    'Jimeta',
    'Mubi',
    'Numan',
    'Ganye',
    'Toungo',
    'Wuro Kila',
    'Poma',
    'Gombi',
    'Hong',
    'Michika',
    'Madagali',
    'Mayo Belwa',
    'Fufore',
    'Song',
    'Teungo',
    'Demsa',
    'Guyuk',
    'Shelmi',
    'Kojoli',
    'Lamurde',
  ],
  'Akwa Ibom': [
    'Uyo',
    'Eket',
    'Ikot Ekpene',
    'Oron',
    'Ikot Abasi',
    'Itu',
    'Abak',
    'Etinan',
    'Oko Ita',
    'Ikot Okoro',
    'Nung Udoe',
    'Ibesikpo',
    'Ikot Oku Ikono',
    'Ndon Eyo',
    'Odot',
    'Udesi',
    'Ikot Akpa Nkuk',
    'Ukanafun',
    'Eastern Obolo',
    'Mkpat Enin',
  ],
  Anambra: [
    'Awka',
    'Onitsha',
    'Nnewi',
    'Aguata',
    'Ogbaru',
    'Ihiala',
    'Nkpor',
    'Otuocha',
    'Aguleri',
    'Umunze',
    'Ekwulobia',
    'Alor',
    'Nnobi',
    'Ojoto',
    'Uga',
    'Igboukwu',
    'Awkuzu',
    'Nteje',
    'Omasi',
    'Umuerum',
  ],
  Bauchi: [
    'Bauchi',
    'Azare',
    "Jama'are",
    'Katagum',
    'Misau',
    'Dass',
    'Shadowanka',
    'Toro',
    'Ningi',
    'Alkaleri',
    'Giade',
    'Shira',
    'Zungur',
    'Lame',
    'Sade',
    'Dindima',
    'Gamawa',
    'Yamrat',
    'Kafin Madaki',
    'Burra',
  ],
  Bayelsa: [
    'Yenagoa',
    'Brass',
    'Ogbia',
    'Sagbama',
    'Ekeremor',
    'Nembe',
    'Oporoma',
    'Amassoma',
    'Odi',
    'Kaiama',
    'Peretorugbene',
    'Ogboloma',
    'Akassa',
    'Twon-Brass',
    'Okpoama',
    'Ogbia Town',
    'Oloibiri',
    'Sangana',
    'Okoroma',
    'Koluama',
  ],
  Benue: [
    'Makurdi',
    'Gboko',
    'Otukpo',
    'Katsina-Ala',
    'Adikpo',
    'Oju',
    'Akegh',
    'Erihii',
    'Ukumu',
    'Ahile',
    'Tse-Anyar',
    'Cheagbe',
    'Ugba',
    'Utonkon',
    'Ugbokpo',
    'Obarike-Ito',
    'Iwarnyam',
    'Apa',
    'Agatu',
    'Obagaji',
  ],
  Borno: [
    'Maiduguri',
    'Bama',
    'Dikwa',
    'Gwoza',
    'Biu',
    'Askira',
    'Fugu Dallari',
    'Budun Gulum',
    'Kasacciya',
    'Damboa',
    'Konduga',
    'Magumeri',
    'Gubio',
    'Kukawa',
    'Monguno',
    'Ngala',
    'Kala-Balge',
    'Dikwagubio',
    'Mafa',
    'Jere',
  ],
  'Cross River': [
    'Calabar',
    'Ugep',
    'Ogoja',
    'Ikom',
    'Obudu',
    'Obanliku',
    'Ndebiji',
    'Akamkpa',
    'Bekwarra',
    'Biase',
    'Bakassi',
    'Yakurr',
    'Abi',
    'Etung',
    'Obubra',
    'Akpabuyo',
    'Odukpani',
    'Isangole',
    'Okundi',
    'Bansan',
  ],
  Delta: [
    'Asaba',
    'Warri',
    'Sapele',
    'Ughelli',
    'Agbor',
    'Burutu',
    'Kwale',
    'Obiaruku',
    'Abraka',
    'Patani',
    'Koko',
    'Ozoro',
    'Ogwashi-Uku',
    'Umunede',
    'Akumazi',
    'Owa-Oyibu',
    'Ute-Okpu',
    'Owa-Alero',
    'Illah',
    'Ubulu-Uku',
  ],
  Ebonyi: [
    'Abakaliki',
    'Afikpo',
    'Onueke',
    'Edda',
    'Ishielu',
    'Ezza',
    'Ikwo',
    'Uburu',
    'Isiaka',
    'Ndibe',
    'Amasiri',
    'Okposi',
    'Nguzu Edda',
    'Amachi',
    'Ugbodo',
    'Nkalagu',
    'Ezzamgbo',
    'Amagu',
    'Agbaja',
    'Onicha',
  ],
  Edo: [
    'Benin City',
    'Auchi',
    'Ekpoma',
    'Igueben',
    'Uromi',
    'Sabongida',
    'Emioboma',
    'Iguobazuwa',
    'Fugar',
    'Ugbegun',
    'Okada',
    'Ubiaja',
    'Igara',
    'Evbuekoi',
    'Ehor',
    'Ologbo',
    'Urhonigbe',
    'Opoji',
    'Ewohimi',
    'Igbanke',
  ],
  Ekiti: [
    'Ado Ekiti',
    'Ikere',
    'Ise',
    'Emure',
    'Aramoko',
    'Efon',
    'Ode-Ekiti',
    'Igbemo',
    'Ijan',
    'Ayetoro',
    'Ilupeju',
    'Omuo',
    'Ikole',
    'Otun',
    'Okemesi',
    'Igede',
    'Oye',
    'Isan',
    'Ikoro',
    'Ido',
  ],
  Enugu: [
    'Enugu',
    'Nsukka',
    'Agbani',
    'Awgu',
    'Udi',
    'Oji River',
    'Nkanu',
    'Uzo Uwani',
    'Igbo Eze',
    'Opi',
    'Eha Amufu',
    'Akegbe',
    'Amagunze',
    'Ibagwa',
    'Obollo',
    'Nkerefi',
    'Amankanu',
    'Ogbodo',
    'Nara',
    'Amaokwe',
  ],
  'Federal Capital Territory': [
    'Agyana',
    'Bago',
    'Bandagi',
    'Dapala',
    'Ebagi',
    'Gbogbogo',
    'Kebba',
    'Manderegi',
    'Nahalati Sabo',
    'Nah. Tosho',
    'Nuku',
    'Panagana',
    'Rimba',
    'Uboshenu',
    'Yawule',
    'Abuja',
    'Adagba',
    'Afo',
    'Akori',
    'Alampa',
    'Allu',
    'Ayaba',
    'Bari-Bezi',
    'Bazi-Bezi',
    'Busga',
    'Chakun',
    'Chundugo',
    'Dabbare',
    'Dara',
    'Dewu',
    'Domi',
    'Dum',
    'Ekki',
    'Fakon Tando',
    'Gadabiri',
    'Gari',
    'Gasakba',
    'Gasukpa',
    'Gawu',
    'Gawun',
    'Gidan Maisaye',
    'Gurdi',
    'Guruza',
    'Gwanda',
    'Gwona',
    'Jamigbe',
    'Kafako',
    'Kpace',
    'Kularida',
    'Kutara',
    'Kwago',
    'Kwakwa',
    'Kyawu',
    'Lafia Yaba',
    'Madechi',
    'Managi',
    'Nadichi',
    'Nagun',
    'Nassarawa',
    'Nowog',
    'Nyembo',
    'Pako Base',
    'Panagu',
    'Pandaji',
    'Pankuru',
    'Panpari',
    'Piowe',
    'Sabongida',
    'Sarowo-Abdu',
    'Selifulyu',
    'Shadad',
    'Soitan',
    'Takpeshi',
    'Talpa',
    'Tanaga',
    'Wapa',
    'Yelwa',
    'Yelwa Gawu',
    'Zuwa',
    'Abacha Barracks',
    'Apo',
    'Damagaza',
    'Dantata',
    'Durumi I',
    'Durumi II',
    'Durumi III',
    'Dutse',
    'Garki Village',
    'Gudu',
    'Guzape',
    'Kobi',
    'Kurumduma',
    'NEPA Village',
    'Wumba',
    'Airport',
    'Barowa',
    'Damakuba',
    'Dandi',
    'Dayisa',
    'Dodo',
    'Gbenduniya',
    'Gbessa',
    'Gora',
    'Gosa',
    'Gud Pasali',
    'Gui',
    'Gwako',
    'Iddo Maaji',
    'Iddo Pada',
    'Iddo Sabo',
    'Iddo Sarki',
    'Iddo Tudunwada',
    'Koloke',
    'Makana',
    'Makanima',
    'Nuwalogye',
    'Sauka',
    'Takilogo',
    'Toge',
    'Tunga Kwaso',
    'Tungan Jika',
    'Tungan Wakili Isa',
    'Zamani',
    'Bagusa',
    'Dei-die',
    'Filin Dabo',
    'Filin Dabo I',
    'Filin Dabo II',
    'Gwagwa',
    'Kaba',
    'Kagini',
    'Karsana I',
    'Karsana II',
    'Karsana III',
    'Saburi I',
    'Saburi II',
    'Tasha',
    'Zaudna',
    'Gwarinpa Fed. Housing',
    'Gwarinpa Life Camp',
    'Gwarinpa Village',
    'Kado Federal Housing',
    'Kado Village',
    'Katampe',
    'Kuchigoro',
    'Mabushi',
    'Utako',
    'Basan Jiwa',
    'Gyeda',
    'Hulumi',
    'Idu',
    'Idu Gwari',
    'Jiwa',
    'Karmo Sabo',
    'Karmo Tsoho',
    'Paipe',
    'Tungan Dallatu',
    'Tungan Madaki',
    'Zhidu',
    'Aleyita',
    'Burum',
    'Dogori Gada',
    'Galadimawa',
    'Kabusa',
    'Ketti',
    'Lokogoma',
    'Lugbe',
    'Piwoyi',
    'Pykasa',
    'Sabon Lugbe',
    'Sheretti',
    'Takushara',
    'Wani',
    'Zhidu',
    'Zidna',
    'Aleku',
    'Damakasa',
    'Damakusa',
    'Gidan Boyi',
    'Gidan Kaka',
    'Gidan Kwano',
    'Karshi',
    'Kupayi',
    'Kusaki',
    'Kutasa',
    'Odu',
    'Tunga',
    'Ugamada',
    'Ungwan Tiv',
    'Jikwoyi',
    'Karu Site (FHA)',
    'Karu Village',
    'Angawa Bawa',
    'Gbagarape',
    'Kugbo',
    'Nyanya Site-Area A-F',
    'Nyanya Village/Gwandara',
    'Nyanya Village/Gwari',
    'Ajata',
    'Angwan Sako',
    'Anka',
    'Badna',
    'Chori Bisa',
    'Gidan Ajiya',
    'Gidan Mangoro',
    'Gugugu',
    'Kpepegyi',
    'Kurudu',
    'Kurudu Gwandara',
    'Kwoi',
    'Madalla',
    'Munapeyi Kasa',
    'Munapeyi Sama',
    'Orozo I',
    'Orozo II',
    'Sabon Gari',
    'Wowo',
    'Apugye',
    'Barago',
    'Baran Rafi',
    'Barangoni',
    'Barapa',
    'Bazango Bwari',
    'Bunko',
    'Byazhi',
    'Chikale',
    'Dankoru',
    'Dauda',
    'Donabayi',
    'Duba',
    'Dutse Alhaji',
    'Gaba',
    'Galuwyi',
    'Gidan Babachi',
    'Gidan Baushe',
    'Gidan Pawa',
    'Gudupe',
    'Gutpo',
    'Igu',
    'Jigo',
    'Kaima',
    'Karaku',
    'Karawa',
    'Kasaru',
    'Katampe',
    'Kawadashi',
    'Kawu',
    'Kikumi',
    'Kimtaru',
    'Kogo',
    'Kubwa',
    'Kuchibuyi',
    'Kuduru',
    'Kurumin Daudu',
    'Kute',
    'Kwabwure',
    'Panda',
    'Panunuki',
    'Paspa',
    'Payi',
    'Piko',
    'Rugan S/Fulani',
    'Ruriji',
    'Sabon Gari',
    'Sagwari',
    'Shere',
    'Simape',
    'Sumpe',
    'T/Danzaria',
    'T/Manu',
    'Tokulo',
    'Tudun Wada',
    'Tunga Bijimi',
    'Tunga-Adoka',
    'Tungan Sarkin',
    'Ushafa',
    'Yaba',
    'Yajida',
    'Yaupe',
    'Yayidna',
    'Zango',
    'Zuma',
    'Agota',
    'Akwayi',
    'Akyakyata',
    'Alu wamo',
    'Anguwar Hausawa',
    'Anguwar Sarki',
    'Atopi',
    'Auguwar-Madaki',
    'Bargada Bassa',
    'Basan Zuba',
    'Bassa',
    'Biyu',
    'Boka',
    'Chaboda',
    'Chitumu',
    'Chzako',
    'Dabagayi',
    'Dada',
    'Dada Gongo',
    'Dadabiri',
    'Damin Kara',
    'Dawaki',
    'Didan Tujura',
    'Diko',
    'Dikwa Gwari',
    'Dikwa Kotwa',
    'Dobi',
    'Doni',
    'Doruwa',
    'Eabodo',
    'Garin Godoso',
    'Gbadolo',
    'Gerin Angulu',
    'Gidan Ango',
    'Gidan Bala',
    'Gidan Dandu',
    'Gidan Gade',
    'Gidan Golo',
    'Gidan Yaro',
    'Goi',
    'Goi Sabo',
    'Gongo',
    'Gulupe',
    'Gurebare',
    'Gurfata',
    'Gurfata Sabo',
    'Gwako',
    'Gwale',
    'Gwari',
    'Gwaywalada',
    'Gyabiri',
    'Hanagada Abdu',
    'Hanagada Bassa',
    'Ibbo',
    'Ibwa',
    'Ibwa Sarki',
    'Ikwa',
    'Isom Bassa',
    'Isom Fulani',
    'Jalita Gongo',
    'Jigodo I',
    'Jiwape',
    'Kaburufi',
    'Kace Bassa',
    'Kace Sabo',
    'Kace Sarki',
    'Kaida Bassa',
    'Kaida Gwari',
    'Kaida Sabo',
    'Kalangu',
    'Kasanki',
    'Kpatawuro',
    'Kutabwche',
    'Kutunku',
    'Kuturpe',
    'Kwalikuzi',
    'Lafiya',
    'Ledi',
    'Ledi Sabo',
    'Madaki Abuche',
    'Maikaraya',
    'Maje Bassa',
    'Maje Tsoho',
    'Makama',
    'Momo Sabo',
    'Pabeyi',
    'Pagada',
    'Pagena I',
    'Paiken Korce',
    'Paiko',
    'Pajana II',
    'Pako',
    'Paso Gwari',
    'Pass Kutawa',
    'Patte',
    'Rafin Zurfi',
    'Rain Zurfi',
    'S/Ganuwa',
    'Sabo',
    'Saboda',
    'Sabon Gari',
    'Shaga I',
    'Shaga II',
    'Shajantara',
    'Shanagu',
    'Shara Bassa',
    'Shibo',
    'Shibo Bassa',
    'Shida',
    'Shidhida',
    'Shinge',
    'Soko',
    'Tsagban Siji',
    'Tsaunia Kura',
    'Tsudna',
    'Tundun Wada',
    'Tung Tsauni',
    'Tunga Makeri',
    'Tungan Adamu',
    'Tungan Auta',
    'Tungan D. Kolo',
    'Tungan Giwa',
    'Tungan Jika',
    'Tungan Kakaki',
    'Tungan Ladan',
    'Tungan M. Hassan',
    'Tungan Maikasuwa',
    'Tungan Pada',
    'Tungan S. Pada',
    'Tungan Salihu',
    'Tungan Tsauni',
    'Ung Gade',
    'Ung. Bassa',
    'Ung. Gwari',
    'Wagu Wase-Gyan',
    'Wuma',
    'Wumi',
    'Wurumbi',
    'Wuye-Wuye',
    'Yaluan Ibwa',
    'Yemipe',
    'Zuba',
    'Achmbi',
    'Aduga',
    'Agwai',
    'Atsauna',
    'Baban Kurmi',
    'Bamishi',
    'Banayi II',
    'Barayi Pada',
    'Bugako',
    'Buzunkure',
    'Chegasu',
    'Chibiri',
    'Chida',
    'Chukuku',
    'Dafara',
    'Damakusa',
    'Damangata',
    'Damwa',
    'Dibe Pada',
    'Dibepe',
    'Dubia',
    'Dudagwari Yamma',
    'Dude',
    'Duma',
    'Duriya',
    'Fafere Tsolo',
    'Gadoro Pada',
    'Gafere Sabo',
    'Ganagu Sabo',
    'Ganaju Sabo',
    'Gando',
    'Gashe',
    'Gaube',
    'Gawu',
    'Gbebasa',
    'Genge-Pada',
    'Gidan Jatau',
    'Gidan-Bawa',
    'Gidid Gwari',
    'Gidigwai II',
    'Ginagu Gwari',
    'Gonge',
    'Gumayi',
    'Gunagu Gwari',
    'Gunfufu',
    'Gwadaji',
    'Gwape II',
    'Gwari',
    'Gwau-Kurmi',
    'Gyawu',
    'Iye',
    'Jaida II',
    'Jeli',
    'Jigwa Isoho',
    'Jigwa Sabo',
    'Kabi',
    'Kabikasa',
    'Kahodahanmu',
    'Kamo G.',
    'Kanzo',
    'Kapa',
    'Kasada',
    'Kashemolo',
    'Kiyi',
    'Kiyi Basa',
    'Kiyi Ganara',
    'Kiyizhi',
    'Ksayarda Hausa',
    'Ksayarda Sabo',
    'Kuja Pada',
    'Kusaki',
    'Kutada',
    'Kutunibo',
    'Kutuop',
    'Kwaku',
    'Lafiya',
    'Lafiya Gwari',
    'Lamiga',
    'Lanto',
    'Madatta',
    'Maugi',
    'Mogada',
    'Nufawa',
    'Padahi',
    'Paggi',
    'Pami',
    'Pasali',
    'Peki',
    'Pima',
    'Rubokya',
    'S/Gwari Genge',
    'Sabon Gwaria',
    'Sauka',
    'Shaji',
    'Sketuko',
    'Takwa Gwari',
    'Takwa Hausawa',
    'Ashara',
    'Dafa',
    'Dakwa',
    'Gumbo',
    'Kilankwa',
    'Kundu',
    'Pai',
    'Wako',
    'Yangoji',
  ],
  Gombe: [
    'Gombe',
    'Kaltungo',
    'Bajoga',
    'Dukku',
    'Billiri',
    'Kumo',
    'Nafada',
    'Deba',
    'Kwami',
    'Doho',
    'Tula',
    'Waja',
    'Amada',
    'Kalshingi',
    'Kuri',
    'Lafiya',
    'Dukkuyel',
    'Bage',
    'Bojude',
    'Dawashi',
  ],
  Imo: [
    'Owerri',
    'Orlu',
    'Okigwe',
    'Oguta',
    'Mgbidi',
    'Awo-Omamma',
    'Mbaise',
    'Ahiara',
    'Obowo',
    'Ehime',
    'Ihite',
    'Ideato',
    'Ngor Okpala',
    'Ogwa',
    'Akatta',
    'Umunumo',
    'Umuagwo',
    'Okwelle',
    'Umuguma',
    'Nkwerre',
  ],
  Jigawa: [
    'Dutse',
    'Hadejia',
    'Birnin Kudu',
    'Gumel',
    'Kazaure',
    'Ringim',
    'Kafin Kaya',
    'Garki',
    'Gagarawa',
    'Maigatari',
    'Sule Tankarkar',
    'Guri',
    'Babura',
    'Roni',
    'Yankwashi',
    'Kaugama',
    'Malam Madori',
    'Gwiwa',
    'Birniwa',
  ],
  Kaduna: [
    'Kaduna',
    'Zaria',
    'Kafanchan',
    'Saminaka',
    'Kagoro',
    'Makera',
    'Brinya',
    'Anguwar Bawa',
    'Kachia',
    'Kujama',
    'Sabon Gari',
    'Kudan',
    'Ikara',
    'Lere',
    'Giwa',
    'Soba',
    'Jaba',
    'Kauru',
    'Kuban',
    'Chikun',
  ],
  Kano: [
    'Kano',
    'Bichi',
    'Dawakin Tofa',
    'Gaya',
    'Rano',
    'Wudil',
    'Kabo',
    'Gwarzo',
    'Karaye',
    'Rogo',
    'Shanono',
    'Tarauni',
    'Tsanyawa',
    'Gezawa',
    'Bagwai',
    'Dambatta',
    'Makoda',
    'Minjibir',
    'Nassarawa',
    'Rimin Gado',
  ],
  Katsina: [
    'Katsina',
    'Daura',
    'Funtua',
    'Malumfashi',
    'Kankia',
    'Dutsin-Ma',
    'Duwan',
    'Idiki',
    'Mani',
    'Kafur',
    'Dandume',
    'Sabuwa',
    'Safana',
    'Batsari',
    'Jibia',
    'Kaita',
    "Mai'Adua",
    'Sandamu',
    'Zango',
    'Baure',
  ],
  Kebbi: [
    'Birnin Kebbi',
    'Argungu',
    'Yelwa',
    'Zuru',
    'Gwandu',
    'Jega',
    'Rafin Kiria',
    'Bodare',
    'Fakai',
    'Arewa',
    'Augie',
    'Bagudo',
    'Dandi',
    'Koko',
    'Maiyama',
    'Sakaba',
    'Shanga',
    'Suru',
    'Wasagu',
    'Alelu',
  ],
  Kogi: [
    'Lokoja',
    'Okene',
    'Idah',
    'Kabba',
    'Ogaminana',
    'Ankpa',
    'Igodo',
    'Dekina',
    'Ajaokuta',
    'Egbe',
    'Mopa',
    'Ogori',
    'Ogodu',
    'Abejukolo',
    'Alloma',
    'Egume',
    'Ihima',
    'Koton Karfe',
    'Okehi',
    'Ponyan',
  ],
  Kwara: [
    'Ilorin',
    'Offa',
    'Jebba',
    'Omu-Aran',
    'Pategi',
    'Lafiagi',
    'Tungansitu',
    'Old Beru',
    'Baruten',
    'Edu',
    'Ekiti',
    'Ifelodun',
    'Irepodun',
    'Kaiama',
    'Moro',
    'Oyun',
    'Isin',
    'Oke Ero',
    'Omupo',
    'Shawo',
  ],
  Lagos: [
    'Lagos',
    'Ikeja',
    'Badagry',
    'Ikorodu',
    'Epe',
    'Lekki',
    'Ikeja',
    'Agege',
    'Ajegunle',
    'Amuwo',
    'Apapa',
    'Ibeju',
    'Ifako',
    'Ilupeju',
    'Isolo',
    'Kosofe',
    'Lagos Island',
    'Mushin',
    'Ojo',
    'Oshodi',
  ],
  Nasarawa: [
    'Lafia',
    'Keffi',
    'Akwanga',
    'Nasarawa',
    'Karu',
    'Doma',
    'Angwan Maji',
    'Awe',
    'Eggon',
    'Keffi',
    'Kokona',
    'Nassarawa',
    'Obi',
    'Toto',
    'Wamba',
    'Agwatashi',
    'Agyaragu',
    'Deddere',
    'Gidan Ausa',
    'Keana',
  ],
  Niger: [
    'Minna',
    'Suleja',
    'Bida',
    'Kontagora',
    'Lapai',
    'Wushishi',
    'Kokodi',
    'Mokwa',
    'Agaie',
    'Agwara',
    'Borgu',
    'Bosso',
    'Chanchaga',
    'Edati',
    'Gbako',
    'Gurara',
    'Katcha',
    'Magama',
    'Mariga',
    'Mashegu',
  ],
  Ogun: [
    'Abeokuta',
    'Sagamu',
    'Ijebu Ode',
    'Ilaro',
    'Ifo',
    'Ota',
    'Lokuta-Tinuade',
    'Ilugun',
    'Ado Odo',
    'Agbara',
    'Ayetoro',
    'Imeko',
    'Ipokia',
    'Odeda',
    'Ogbere',
    'Owode',
    'Sango',
    'Wasimi',
    'Ijebu Igbo',
    'Orile',
  ],
  Ondo: [
    'Akure',
    'Ondo',
    'Owo',
    'Okitipupa',
    'Ikare',
    'Odigbo',
    'Ominla',
    'Oloba',
    'Ago-Dudu',
    'Idanre',
    'Irele',
    'Oka',
    'Igbokoda',
    'Ode',
    'Ifon',
    'Iju',
    'Ilara',
    'Ipinsa',
    'Oba',
    'Okeigbo',
  ],
  Osun: [
    'Osogbo',
    'Ilesa',
    'Ile-Ife',
    'Ede',
    'Iwo',
    'Ikire',
    'Buko',
    'Ejigbo',
    'Gbongan',
    'Ikirun',
    'Ila',
    'Iragbiji',
    'Iree',
    'Odeomu',
    'Okuku',
    'Olupona',
    'Otan',
    'Oyan',
    'Aagba',
    'Apomu',
  ],
  Oyo: [
    'Ibadan',
    'Ogbomoso',
    'Oyo',
    'Iseyin',
    'Saki',
    'Eruwa',
    'Onibuku',
    'Ojoemo',
    'Bale',
    'Aloba Ile',
    'Adeleye',
    'Ibarapa',
    'Iganna',
    'Kisi',
    'Lalupon',
    'Okeho',
    'Otu',
    'Tede',
    'Ago Are',
    'Fiditi',
  ],
  Plateau: [
    'Jos',
    'Bukuru',
    'Shendam',
    'Pankshin',
    'Barkin Ladi',
    'Langtang',
    'Ropp',
    'Ucheregh',
    'Bassa',
    'Bokkos',
    'Kanam',
    'Kanke',
    'Mangu',
    'Mikang',
    'Panyam',
    "Qua'an Pan",
    'Riyom',
    'Wase',
    'Angware',
    'Foron',
  ],
  Rivers: [
    'Port Harcourt',
    'Bonny',
    'Degema',
    'Okrika',
    'Bori',
    'Omoku',
    'Queens Town',
    'Ahoada',
    'Elele',
    'Emohua',
    'Buguma',
    'Ogu',
    'Opobo',
    'Oyigbo',
    'Rumuji',
    'Abonnema',
    'Andoni',
    'Bille',
    'Kono',
    'Obonoma',
  ],
  Sokoto: [
    'Sokoto',
    'Tambuwal',
    'Wurno',
    'Gwadabawa',
    'Isa',
    'Kware',
    'Kaurare',
    'Gidan Almuwa',
    'Binji',
    'Bodinga',
    'Dange',
    'Gada',
    'Goronyo',
    'Gudu',
    'Illela',
    'Kebbe',
    'Rabah',
    'Sabon Birni',
    'Shagari',
    'Tangaza',
  ],
  Taraba: [
    'Jalingo',
    'Wukari',
    'Bali',
    'Takum',
    'Serti',
    'Gembu',
    'Ibi',
    'Lau',
    'Ardo Kola',
    'Bali',
    'Donga',
    'Gashaka',
    'Kurmi',
    'Ussa',
    'Yorro',
    'Zing',
    'Baissa',
    'Didango',
    'Fikyu',
    'Humbu',
  ],
  Yobe: [
    'Damaturu',
    'Potiskum',
    'Gashua',
    'Geidam',
    'Buni Yadi',
    'Nguru',
    'Chungul Jabarari',
    'Bade',
    'Bursari',
    'Fika',
    'Fune',
    'Gujba',
    'Gulani',
    'Jakusko',
    'Karasuwa',
    'Machina',
    'Nangere',
    'Yusufari',
    'Dapchi',
    'Jajimaji',
  ],
  Zamfara: [
    'Gusau',
    'Kaura Namoda',
    'Tsafe',
    'Anka',
    'Talata Mafara',
    'Zurmi',
    'Bakura',
    'Birnin Magaji',
    'Bukkuyum',
    'Bungudu',
    'Gummi',
    'Kaura',
    'Maradun',
    'Maru',
    'Shinkafi',
    'Zumi',
    'Dangulbi',
    'Kaya',
    'Mada',
    'Ruwan Bore',
  ],
}

//
export type StateName = keyof typeof nigerianLgaByStates

export function getLgaByState(state: string): string[] {
  const normalizedState = state.trim().toLowerCase()

  for (const [key, lgas] of Object.entries(nigerianLgaByStates)) {
    if (key.trim().toLowerCase() === normalizedState) {
      return lgas
    }
  }

  return [] // State not found
}

export function getGeopoliticalZoneByState(state: string): string {
  const normalizedState = state.trim().toLowerCase()

  for (const [zone, states] of Object.entries(
    nigerianStatesByGeopoliticalZones,
  )) {
    for (const s of states) {
      if (s.trim().toLowerCase() === normalizedState) {
        return zone
      }
    }
  }

  return '' // State not found in any zone
}

export function getAreasByState(state: string): string[] {
  const normalizedState = state.trim().toLowerCase()

  for (const [key, areas] of Object.entries(nigerianAreasByStates)) {
    if (key.trim().toLowerCase() === normalizedState) {
      return areas
    }
  }

  return []
}
