export const serviceProvidersCategories = [
  'Microgrid Developer',
  'Solar Provider',
]

export const serviceProvidersProductsAndServices = [
  { value: 'Solar Panels', label: 'Solar Panels' },
  { value: 'Batteries', label: 'Batteries' },
  { value: 'Inverters', label: 'Inverters' },
  { value: 'UPS', label: 'UPS' },
  { value: 'Microgrid Advisor', label: 'Microgrid Advisor' },
  { value: 'Edge control Systems', label: 'Edge control Systems' },
  { value: 'Design & Development', label: 'Design & Development' },
  { value: 'Installation & Maintenance', label: 'Installation & Maintenance' },
  { value: 'Generation & Distribution', label: 'Generation & Distribution' },
  { value: 'Monitoring & Control', label: 'Monitoring & Control' },
  { value: 'Automation', label: 'Automation' },
  { value: 'Remote monitoring', label: 'Remote monitoring' },
  { value: 'Grid softwares', label: 'Grid softwares' },
  { value: 'Fuel-cells', label: 'Fuel-cells' },
  { value: 'Asset management', label: 'Asset management' },
  { value: 'wind', label: 'wind' },
]

export const serviceProvidersCoverageAreas = [
  { value: 'All States', label: 'All States' },
  { value: 'Abia', label: 'Abia' },
  { value: 'Adamawa', label: 'Adamawa' },
  { value: 'Akwa Ibom', label: 'Akwa Ibom' },
  { value: 'Anambra', label: 'Anambra' },
  { value: 'Bauchi', label: 'Bauchi' },
  { value: 'Bayelsa', label: 'Bayelsa' },
  { value: 'Benue', label: 'Benue' },
  { value: 'Borno', label: 'Borno' },
  { value: 'Cross River', label: 'Cross River' },
  { value: 'Delta', label: 'Delta' },
  { value: 'Ebonyi', label: 'Ebonyi' },
  { value: 'Edo', label: 'Edo' },
  { value: 'Ekiti', label: 'Ekiti' },
  { value: 'Enugu', label: 'Enugu' },
  { value: 'Federal Capital Territory', label: 'Federal Capital Territory' },
  { value: 'Gombe', label: 'Gombe' },
  { value: 'Imo', label: 'Imo' },
  { value: 'Jigawa', label: 'Jigawa' },
  { value: 'Kaduna', label: 'Kaduna' },
  { value: 'Kano', label: 'Kano' },
  { value: 'Katsina', label: 'Katsina' },
  { value: 'Kebbi', label: 'Kebbi' },
  { value: 'Kogi', label: 'Kogi' },
  { value: 'Kwara', label: 'Kwara' },
  { value: 'Lagos', label: 'Lagos' },
  { value: 'Nasarawa', label: 'Nasarawa' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Ogun', label: 'Ogun' },
  { value: 'Ondo', label: 'Ondo' },
  { value: 'Osun', label: 'Osun' },
  { value: 'Oyo', label: 'Oyo' },
  { value: 'Plateau', label: 'Plateau' },
  { value: 'Rivers', label: 'Rivers' },
  { value: 'Sokoto', label: 'Sokoto' },
  { value: 'Taraba', label: 'Taraba' },
  { value: 'Yobe', label: 'Yobe' },
  { value: 'Zamfara', label: 'Zamfara' },
]

export const serviceProviderConnectionMode = [
  'Remote (off-grid)',
  'Grid-connected',
  'Networked',
]

export const serviceProviderBusinessClassification = [
  'wholesaler',
  'retailer',
  'manufacturer',
  'Small scale',
  'Medium scale',
  'Large scale',
]
